### ISSUE TITLE
Very nice!

### ISSUE THREAD

**Issue by dawsonbotsford** [aleclarson/steal#1]
I LOVE :heart:  this idea, nice job making it so clear how it works. I recommend doing a short comparison to the `delete` function and explain that that call only returns true or false. Then talk about how yours works different. Maybe try a catch phrase like 

> "Like Array.prototype.pop, but for objects"

**Comment by aleclarson** [comment]
Thanks for the feedback! Updated the README and tagline as requested. :+1:
